[tool.poetry]
name = "ai-admin"
version = "0.1.0"
description = "正心全栈"
authors = ["ZengHedong <Zenghedong@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
