# Generated by Django 2.2.12 on 2022-01-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuanLiYuan',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('zhiwu', models.CharField(default='', max_length=28, verbose_name='职务')),
                ('photo', models.ImageField(default='', upload_to='admin/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name_plural': '管理员列表',
                'db_table': 'GuanLiYuan',
            },
        ),
        migrations.CreateModel(
            name='KeCheng',
            fields=[
                ('id', models.CharField(default='', max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('kecheng', models.CharField(default='', max_length=128, verbose_name='课表')),
                ('ok', models.CharField(choices=[('ok', '是'), ('no', '否')], default='no', max_length=6, verbose_name='是否已评价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name_plural': '选课表',
                'db_table': 'Kecheng',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(default='', max_length=28, verbose_name='姓名')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
                ('xueyuan', models.CharField(default='', max_length=28, verbose_name='学院')),
                ('banji', models.CharField(default='', max_length=28, verbose_name='班级')),
                ('xuehao', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('photo', models.ImageField(default='', upload_to='Students/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name_plural': '学生列表',
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('name', models.CharField(default='', max_length=28, verbose_name='姓名')),
                ('password', models.CharField(default='', max_length=28, verbose_name='密码')),
                ('teacher_id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='教师id')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('photo', models.ImageField(default='', upload_to='teacher/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name_plural': '教师列表',
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TiKu_1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timu', models.TextField(default='', max_length=210, verbose_name='题目')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name_plural': '题库',
                'db_table': 'TiKu_1',
            },
        ),
        migrations.CreateModel(
            name='PingJia',
            fields=[
                ('id', models.CharField(default='', max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('s_daan1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案1')),
                ('s_daan2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案2')),
                ('s_daan3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案3')),
                ('s_daan4', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案4')),
                ('s_daan5', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案5')),
                ('s_daan6', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案6')),
                ('s_daan7', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案7')),
                ('s_daan8', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案8')),
                ('s_daan9', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案9')),
                ('s_daan10', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='学生答案10')),
                ('s_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='平均成绩')),
                ('s_liuyan', models.TextField(default='', max_length=210, null=True, verbose_name='学生留言')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('kecheng', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login.KeCheng', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '评价表',
                'db_table': 'PingJia',
            },
        ),
        migrations.AddField(
            model_name='kecheng',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.Teachers', verbose_name='教工号'),
        ),
        migrations.AddField(
            model_name='kecheng',
            name='xuehao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.Students', verbose_name='学号'),
        ),
    ]
