# Generated by Django 2.2.12 on 2022-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=60, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='password',
            field=models.CharField(default='', max_length=60, verbose_name='密码'),
        ),
    ]
