"""empty message

Revision ID: 05dff11f9e2f
Revises: 04f4906a9a4e
Create Date: 2024-02-21 10:08:19.229020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dff11f9e2f'
down_revision = '04f4906a9a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email-captcha', schema=None) as batch_op:
        batch_op.drop_index('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email-captcha', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    # ### end Alembic commands ###
